sdm: Fix -Wformat errors with explicit void* -> char* cast.
hardware/qcom/sm7250/display/sde-drm/drm_plane.cpp:439:12: error: format specifies type 'char *' but the argument has type 'void *' [-Werror,-Wformat]
           blob->data, blob->length);
           ^~~~~~~~~~

hardware/qcom/sm7250/display/sde-drm/drm_connector.cpp:497:12: error: format specifies type 'char *' but the argument has type 'void *' [-Werror,-Wformat]
           blob->data, blob->length);
           ^~~~~~~~~~

hardware/qcom/sm7250/display/sde-drm/drm_connector.cpp:580:12: error: format specifies type 'char *' but the argument has type 'void *' [-Werror,-Wformat]
           blob->data, blob->length);
           ^~~~~~~~~~

hardware/qcom/sm7250/display/sde-drm/drm_crtc.cpp:308:12: error: format specifies type 'char *' but the argument has type 'void *' [-Werror,-Wformat]
           blob->data, blob->length);
           ^~~~~~~~~~

Bug: http://b/155835175
Bug: http://b/169166735
Test: m
Change-Id: Ie9c174aaa38bb9a492b433b27ebafcfe1e1fc115
Merged-In: Ie9c174aaa38bb9a492b433b27ebafcfe1e1fc115
(cherry picked from commit d6c77ce7fae676a501db369ea2c2378f14cda6b2)